version: "3"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:latest
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: spring_rest_db
      MYSQL_ROOT_PASSWORD: 2605
    restart: always
  app:
    build: ./
    container_name: java-advanced
    ports:
    - 8080:8080
    restart: always


